"""empty message

Revision ID: db576644ebc8
Revises: 77e6b97cccd2
Create Date: 2021-06-11 20:24:51.085622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db576644ebc8'
down_revision = '77e6b97cccd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit_card', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'credit_card')
    # ### end Alembic commands ###
