"""empty message

Revision ID: 7182b937b6c5
Revises: 9f8ca7431b9c
Create Date: 2021-05-13 23:22:03.831994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7182b937b6c5'
down_revision = '9f8ca7431b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
