"""empty message

Revision ID: 48c3c3d8b625
Revises: 2ec10a38cf15
Create Date: 2021-06-11 19:00:39.043210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c3c3d8b625'
down_revision = '2ec10a38cf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit_card', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'credit_card')
    # ### end Alembic commands ###
